name: Update README with GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *" # প্রতি 12 ঘন্টায় auto update
  workflow_dispatch: # চাইলে manually চালাতে পারবে

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mdshahadat
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_people: yes
          plugin_traffic: yes
